name: Upload Photos To Tencent COS

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install coscli
        run: |
          wget https://cosbrowser.cloud.tencent.com/software/coscli/coscli-linux
          chmod +x coscli-linux
          sudo mv coscli-linux /usr/local/bin/coscli

      - name: Configure coscli
        run: |
          coscli config add \
            -i ${{ secrets.COS_SECRET_ID }} \
            -k ${{ secrets.COS_SECRET_KEY }} \
            -b ${{ secrets.COS_BUCKET }} \
            -r ${{ secrets.COS_REGION }} \
            -a default

      - name: Sync files to COS
        run: |
          coscli sync "${GITHUB_WORKSPACE}/" cos://default/ \
            --recursive \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".gitignore"